### ISSUE TITLE
Not RFC6901 compliant

### ISSUE THREAD

**Issue by remexre** [sagold/json-pointer#1]
Check [section 3](https://tools.ietf.org/html/rfc6901#section-3); you need to support escaping `~` and `/`. As a test case, both of these should evaluate to `true`:

```js
gsonPointer.get({
    "~0~1": false,
    "~/": true,
}, "#/~0~1");

gsonPointer.get({
    "~0~1/0/1": true,
    "~00~01~10~11": false,
}, "#/~00~01~10~11");
```

**Comment by remexre** [comment]
Also, you should probably make it clear that you're using the [URI Fragment Identifier Representation (section 6)](https://tools.ietf.org/html/rfc6901#section-6); otherwise, the `#` would be omitted from the front.

**Comment by sagold** [comment]
Hi remexre.

Thank you very much for your feedback. The documentation already mentioned the missing _rfc 6901_ support, but i can totally understand the misapprehension due to my very short description.

I made two changes according to your feedback.

1. this json-pointer implementation now confirms to _rfc 6901_ with version v2.2.0
2. I (hopefully) made it clear that the URI Fragment is only treated as syntactic sugar and that it therefore differs from the spec.

Furthermore, thank you for the test cases. They did catch a bug.

Regards.
sagold
